export default [
  { name: 'Allianz', id: 'L_ALLIANZPARQUE', dist: 'allianzparque' },
  { name: 'Clube Netshoes', id: 'L_CLUBENETSHOES', dist: 'clubenetshoes' },
  { name: 'ComSchool', id: 'L_COMSCHOOL', dist: 'comschool' },
  { name: 'Estante Virtual', id: 'L_ESTANTEVIRTUAL', dist: 'estantevirtual' },
  { name: 'Fluxo', id: 'L_FLUXO', dist: 'fluxo' },
  { name: 'Freelace', id: 'L_FREELACE', dist: 'freelace' },
  { name: 'Gap', id: 'L_GAP', dist: 'gapbrasil' },
  { name: 'Kappa', id: 'L_KAPPA', dist: 'kappa' },
  { name: 'Loja da Chape', id: 'L_CHAPECOENSE', dist: 'lojadachape' },
  { name: 'Loja do Inter', id: 'L_INTERNACIONAL', dist: 'lojadointer' },
  { name: 'NBA', id: 'L_NBA', dist: 'zattini' },
  { name: 'Netshoes', id: 'L_NETSHOES', dist: 'netshoesbr' },
  { name: 'NFL', id: 'L_NFL', dist: 'nflshop' },
  { name: 'Rainha', id: 'L_RAINHA', dist: 'rainha' },
  { name: 'Santos', id: 'L_SANTOS', dist: 'santosstore' },
  { name: 'SP Mania', id: 'L_SAOPAULO', dist: 'saopaulomania' },
  { name: 'Shoestock', id: 'L_SHOESTOCK', dist: 'shoestock' },
  { name: 'Shop Cruzeiro', id: 'L_CRUZEIRO', dist: 'shopcruzeiro' },
  { name: 'Shop Timão', id: 'L_CORINTHIANS', dist: 'shoptimao' },
  { name: 'Shop Vasco', id: 'L_VASCO', dist: 'shopvasco' },
  { name: 'Topper', id: 'L_TOPPER', dist: 'topper' },
  { name: 'WSL', id: 'L_WSL', dist: 'wslstore' },
  { name: 'Zattini', id: 'L_ZATTINI', dist: 'zattini' },
]